# Generated by Django 4.1 on 2022-09-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translates',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Перевод', 'verbose_name_plural': 'Переводы'},
        ),
        migrations.AlterField(
            model_name='translates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='translates',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='translates',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='translates',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='translates',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название произведения'),
        ),
        migrations.AlterField(
            model_name='translates',
            name='title_in_the_original_language',
            field=models.CharField(max_length=200, verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='translates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='translates',
            name='year_of_release',
            field=models.CharField(max_length=4, verbose_name='Год релиза'),
        ),
    ]
